### ISSUE TITLE
Extend Extract Solution build task to use Power Platform CLI command

### ISSUE THREAD

**Issue by satyarkar** [Capgemini/powerapps-project-template#55]
Extract Solution build task is using SolutionPackager tool to unpack the solution zip file.
Replace SolutionPackager with Power Platfomr CLI 'solution unpack' command which provides the ability to unpack solution zip files after they have been exported.

**Comment by tdashworth** [comment]
I believe packing can be done the same?

**Comment by tdashworth** [comment]
Also, would be good to add a minimum version for the PAC tool.
