### ISSUE TITLE
'Sarif Viewer Build Tab' is deprecated

### ISSUE THREAD

**Issue by filcole** [Capgemini/powerapps-project-template#69]
## Describe the bug
The 'Sarif Viewer Build Tab' used by `yo @capgeminiuk/powerapps-project:azuredevops` is deprecated, and replaced by 'SARIF SAST Scans Tab'

## To reproduce
Run `yo @capgeminiuk/powerapps-project:azuredevops` notice 'Sarif Viewer Build Tab' extension is installed

## Expected behaviour
SARIF SAST Scans Tab is installed
https://marketplace.visualstudio.com/items?itemName=sariftools.scans

## Screenshots
![image](https://user-images.githubusercontent.com/6078398/160147781-7420f211-c4a0-4de4-b752-7737afe69204.png)

## Environment (please complete the following information):
 - yo version: yo@4.3.0
 - generator-powerapps-project version: @capgeminiuk/generator-powerapps-project@0.4.1
 - Power Apps CLI version: 1.13.4+g79187cf
 - Power Apps environment version:  n/a

**Comment by tdashworth** [comment]
@filcole Thanks for raising this! I'll put in a change in the coming days.
